[unstable]
build-std-features = ["compiler-builtins-mem"] # Include functions for memory copy, moving and comparing
build-std = ["core", "compiler_builtins"] # Recompile core for our target

[build]
target = "x86_64-rust_os.json"